[package]
name = "neuralops"
version = "0.1.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
build = "build.rs"

[lib]
name = "neuralops"
path = "src/lib.rs"

[[bin]]
name = "train-mnist"
path = "tools/train-mnist.rs"

[[bin]]
name = "train-cifar10"
path = "tools/train-cifar10.rs"

[build-dependencies]
gcc = "*"

[dependencies]
byteorder = "*"
float = "*"
rand = "*"
densearray = { path = "../libdensearray" }
iter_utils = { path = "../libiter_utils" }
nnpack = { path = "../libnnpack" }
operator = { path = "../liboperator" }
rng = { path = "../librng" }
sharedmem = { path = "../libsharedmem" }
